### ISSUE TITLE
Injector can't find black ops cold war even when its open

### ISSUE THREAD

**Issue by SuperGodzillav2** [ate47/atian-cod-tools#2]
### Tools version

1.13.1

### Game

Black Ops Cold War

### Platform

Windows

### Description of the issue

the injector can't seem to find my game, im really dumbfounded
![Screenshot 2024-08-12 231044](https://github.com/user-attachments/assets/503c9ec4-cfaa-424f-a8e2-b0e0e21f1928)
 here idk what to do

### Do I want to contribute to fix it?

None

**Comment by ate47** [comment]
Did you try to start it as administrator?
