### ISSUE TITLE
Multiplayer Maps and Game Modes

### ISSUE THREAD

**Issue by IRONB0SS** [ate47/atian-cod-tools#4]
Hey Sir, How are You?

I saw Zhm86 used your tool to unlock Zombies Easter egg so I'm here to asking help, Zhm86 also unlocked the maps on jailbroken PS4 with Cheats and patches but I thought it would be awesome if there was a way to show the hidden maps on the game maps list just like the below screenshot I took from an online PS4
![IMG_20241113_010407_265.jpg](https://github.com/user-attachments/assets/d62c3f74-d581-44bd-8c2f-2c828b820b3e)

![IMG_20241113_010407_244.jpg](https://github.com/user-attachments/assets/65e366bf-33d8-447a-bcb6-f85dc805cdac)

Also there are some hidden game modes too, we need Gun Game badly :)
![IMG_20241113_010407_459.jpg](https://github.com/user-attachments/assets/e4124330-13bd-4d2e-933b-7861a26c7a98)

This is his latest patch file

[CoD_BlackOpsColdWar_PS4_v1_27_CUSA24267_Unlock_All_in_offline_TEST.zip](https://github.com/user-attachments/files/17723112/CoD_BlackOpsColdWar_PS4_v1_27_CUSA24267_Unlock_All_in_offline_TEST.zip)

CODs eboot.bin (we're playing 1.27 cause its more stable)
https://mega.nz/folder/Zqh0lLzR#WR1chv4WS_PHqO0V0lue2w

could you help us? Thanks in advance 🙌

**Comment by ate47** [comment]
For this kind of questions, you can go in the [discussions tab](https://github.com/ate47/atian-cod-tools/discussions).

Then I don't know anything except how to read/write in memory for the PS4. I know that we had to replace the lua scripts for bo4 to get that, but same, I don't know anything about luajit. Maybe ask zhm86

**Comment by IRONB0SS** [comment]
Thanks Buddy
